sonar.projectKey=AstreHD_Code-quality-and-CI-CD
sonar.organization=astrehd

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/**,**/controller/**,setup.py,test_wheel.py
